spring:
  application:
    name: projeto-todo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto-todo?useTimezone=true&serverTimezone=UTC
    username: root
    password: andrei123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
